### ISSUE TITLE
Background page errors when closing PDF tab in Chrome extension

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/browser-extension#24]
_Originally opened as https://github.com/hypothesis/h/issues/3095 by @robertknight._

### Steps to reproduce
1. Go to any PDF document, e.g. http://www.orimi.com/pdf-test.pdf or http://users.clas.ufl.edu/burt/KafkaKierkegaardBible/BorgesTheCircularRuins.pdf
2. Activate the H Chrome extension
3. Open the background page for the extension under chrome://extensions
4. Close the tab opened in step 1.

### Expected behaviour

No errors in the Chrome extension background page

### Actual behaviour

This error is seen in the Chrome extension background page and reported to Sentry:

```
Unchecked runtime.lastError while running browserAction.setBadgeText: No tab with id: 614.
    at BrowserAction.update (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/extension.bundle.js:3313:25)
    at TabState.onTabStateChange [as onchange] (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/extension.bundle.js:3689:21)
    at TabState.setState (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/extension.bundle.js:4560:12)
    at Object.updateTabDocument [as callback] (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/extension.bundle.js:3800:13)
_generated_background_page.html:1 Unchecked runtime.lastError while running browserAction.setTitle: No tab with id: 614.
    at BrowserAction.update (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/extension.bundle.js:3315:25)
    at TabState.onTabStateChange [as onchange] (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/extension.bundle.js:3689:21)
    at TabState.setState (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/extension.bundle.js:4560:12)
    at Object.updateTabDocument [as callback] (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/extension.bundle.js:3800:13)
_generated_background_page.html:1 Error in response to tabs.get: TypeError: Cannot read property 'id' of undefined
    at Object.updateTabDocument [as callback] (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/extension.bundle.js:3792:28)
    at TabState.onTabStateChange [as onchange] (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/extension.bundle.js:3690:18)
    at TabState.setState (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/extension.bundle.js:4560:12)
    at Object.updateTabDocument [as callback] (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/extension.bundle.js:3800:13)
_generated_background_page.html:1 Unchecked runtime.lastError while running tabs.get: No tab with id: 614.
    at TabState.onTabStateChange [as onchange] (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/extension.bundle.js:3690:18)
    at TabState.setState (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/extension.bundle.js:4560:12)
    at Object.updateTabDocument [as callback] (chrome-extension://bjfhmglciegochdpefhhlphglcehbmek/extension.bundle.js:3800:13)
_generated_background_page.html:1 Unchecked runtime.lastError while running browserAction.setIcon: No tab with id: 614.
```

### Browser/system information

Reported on Chrome 50 under Ubuntu 15.10.
Verified on Chrome 58.0.3013.3 (Official Build) dev (64-bit) under Mac OS X 10.12.3.

### Additional information

Apparently this was at some point reported to Sentry, but I can't find evidence of that at the moment.

**Comment by robertknight** [comment]
This issues looks to have been resolved at some point, possibly as part of the Manifest V3 migration effort. I can't reproduce using extension v1.1259.0.2.
