### ISSUE TITLE
Timeout deploying to the Firefox addons store

### ISSUE THREAD

**Issue by esanzgar** [hypothesis/browser-extension#583]
The Jenkins release process fails to upload the browser-extension to the Firefox addons store:

```
Error: Signing took too long to complete; last status: 
    at Timeout._onTimeout (/data/jenkins/workspace/browser-extension_master/node_modules/sign-addon/dist/webpack:/sign-addon/src/amo-client.js:322:11)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)

Signing Firefox QA extension failed
```

**Comment by robertknight** [comment]
We "temporarily" disabled signing of Firefox extensions when this happened, and deployments have been migrated from Jenkins to GitHub Actions since then. We should retry enabling FF extension signing at some point.
